### ISSUE TITLE
Lodash framework - Replace hand-made functions

### ISSUE THREAD

**Issue by Gulix** [Gulix/geckos#114]
Underscore framework needs to be added to the project.
Then, various methods need to be replaced by Underscore methods to enhance maintainability

**Comment by Gulix** [comment]
Well, maybe Lodash will be more suited, as it's somehow the successor of Underscore ?

**Comment by court-jus** [comment]
I use Lodash on a daily basis and its awesome, you won't be lost if you already know Underscore

**Comment by Gulix** [comment]
Lodash it is !

**Comment by Gulix** [comment]
Well, I make use of lodash in Geckos now.
I close this issue as the replacement is made step by step .
