### ISSUE TITLE
Problems running locally

### ISSUE THREAD

**Issue by Dalick** [Gulix/geckos#115]
I downloaded the source files and launched index.html. When I did so, the home page loaded with the five tabs, but clicking on the tabs does not produce any results. I also do not see the Welcome to Geckos introduction text, nor do the Documentation and Github page buttons show up like they do when I go to the demo page you have running for Geckos.

I have tried launching the file on the latest Google Chrome as well as IE 11, and both browsers produce the same results.

Is there something that I need to edit in the index.html to get this to work locally, or do I need to setup a special directory structure? All I have done so far is download the source for the Master branch and extracted the files to a folder. I then double click on index.html.

**Comment by Gulix** [comment]
I'm currently using RequireJS to load dependencies and templates. But that uses XMLHttpRequest, and that's not authorized by Chrome and IE. Firefox seems to works fine (I test on it mainly).
I personnaly set up a light web server on windows to have the code run on a "server configuration" : http://fenixwebserver.com/

As only the `file:` request are blocked by Chrome, I will look into it to see if a solution exists.

**Comment by Dalick** [comment]
I installed Firefox and tried running Geckos locally using Firefox. I am not able to fully load the home page and clicking the tabs takes me to the correct page. I did notice that the Template tab looks different when I run it locally versus your online demo. In your online demo you are able to enter and edit the template directly on the webpage. When I run it locally I do not have this option. I just have images of Arabesque and Basic Effect templates and the option to use one of them. I do not see an option to enter my own or to load one from a file.

**Comment by Gulix** [comment]
Try the last release or this version of the master branch : b94c6fb4cb7deb9d043bce8b8ba3c103b398549e
The list of templates is a Work in Progress (see #30 )

You can also edit the `src/js/config.js` and set this : 

```
templates: {
  // Does Geckos allow the Edition of the template ?
  editionMode: true,
  // Does Geckos display a List of templates to be selected ?
  listMode: true,
  // Mode that Geckos use by default ('list' or 'edition')
  defaultMode: "list"
}
```

But clearly, the master branch is an in-progress work. The release-one are much stable (and the demo page is up-to-date with the latest release).

**Comment by Gulix** [comment]
I close this Issue.
Geckos is not meant to be used locally (or at least through a local server like Fenix).
It could work, but some elements are not meant to be used that way (depending on your browser)
