### ISSUE TITLE
Vertical Text Alignment

### ISSUE THREAD

**Issue by Dalick** [Gulix/geckos#116]
I would like to request an option for vertical text alignment so that a title bar can run up the side of a card. Currently it appears that you can only create a horizontal text box. I would like the ability to either be able to rotate the text box so that it is vertically aligned, or have an option that tells the text box that the text inside it should be vertically aligned.

**Comment by Gulix** [comment]
http://fabricjs.com/docs/fabric.Textbox.html#angle

The `angle` property of a TextBox seems to be what you're looking for. Can you test it and tell me if that's what you need ? 
Otherwise, I can look into it. Put a picture of what you're waiting (just a draft), and I'll see how to obtain it.

**Comment by Dalick** [comment]
I tested the angle property and you are correct, it does what I was looking for. Thank you.
