### ISSUE TITLE
Template for Frostgrave Monsters

### ISSUE THREAD

**Issue by Gulix** [Gulix/geckos#170]
Adapting my Frostgrave template (seen on [MSETemplates](https://github.com/Gulix/MSETemplates/releases/tag/v1.5.0)) to Geckos. The border color could be modified (SVG), and a variant for Ghost Archipelagos (A ruin, a Palm Tree, other ideas) could be added.

![](https://cloud.githubusercontent.com/assets/9212910/13613606/267af48a-e56d-11e5-8d6b-d979ddc2cd99.jpg)

**Comment by Dreadaxe** [comment]
Le texte n'est pas trop proche de l'image ?
L'image n'est pas centrée verticalement par rapport au texte.
Pour le reste c'est très chouette.

**Comment by Gulix** [comment]
Merci
Pour les 2 points soulevés, ce sont en effet des éléments que je compte améliorer dans ce nouveau template (là, c'est celui réalisé pour Magic Set Editor).

**Comment by Gulix** [comment]
First version done !
