### ISSUE TITLE
Suivi création de template

### ISSUE THREAD

**Issue by Selfyn** [Gulix/geckos#202]
Bonjour et merci tout d'abord de votre travail !

Je cherche à créer un template pour un jeu de carte que je souhaite développer par la suite, le soucis étant que je n'ai aucune connaissance de codage ou autre ... Mais j'ai du temps à donner et une curiosité débordante !
Je me suis donc attelé au tutoriel de création de Template à partir de 0 et je bloque à la 1ère phase : 

Je dois valider le code json dans le template mais je reçois à chaque fois ce message "The template is not valid - .styles[0] - should have required property 'key'".

Sans doute n'est-ce pas grand chose mais je ne dispose pas de moyen technique pour comprendre / réparer cela.
Avez-vous une idée de comment puis-je corriger ce soucis ?

Pensez-vous qu'il soit aisé de créer un template sans aucune connaissance de code ou me faut-il faire appel à quelqu'un d'autre ?

J'emploie Chrome en v. 66.0.3359.170

Et pour le template 

`{
  "styles": [
    {
      "fields": [
        { "name": "name", "label": "Name", "default": "Nobbla " }
      ],
      "canvasFields": [
    
      ],
      "canvasBackground": "#FF0000",
      "canvasWidth": 536,
      "canvasHeight": 750
    }
  ]
}`

**Comment by Gulix** [comment]
Il va falloir que je relise le tutorial. Geckos a évolué depuis son écriture, et certains éléments ne sont peut-être plus à jour.

Les styles, notamment, sont un peu plus complexes (avec l'héritage).

Pour infos, la description des styles : http://www.gulix.fr/geckos/wiki/doku.php?id=en:template:styles

Il manque des éléments à l'objet `styles`

Voici un squelette vierge pour démarrer : 

```
{
  "styles": [
  {
    "fields": [
      { "name": "name", "label": "Name", "default": "Nobbla " }
    ],
    "canvasFields": [
      
    ],
    "canvasBackground": "#FF0000",
    "canvasWidth": 536,
    "canvasHeight": 750,
    "key": "macarte",
    "description": "description",
    "name": "Ma Carte"
  }
  ],
  "description": 
    {
      "description": "Template description",
      "title":"Template title",
      "credits": "by me",
      "key": "unique-template-key",
      "url": "https://github.com/Gulix/geckos/"
    }
}
```

Ici, il manquait l'info `key` qui est obligatoire. La partie "description" du template a aussi été rajoutée.

Mon conseil, pour créer un template, serait plutôt de partir d'un template existant qui peut correspondre au template souhaité, et de l'adapter.

**Comment by Gulix** [comment]
Code du tutorial mis à jour, normalement.
